input Pagination {
	page: Int = 1
	limit: Int = 5
}

type Query {
	users(
		pagination: Pagination = {}
		userId: ID
		search: String 
	): [User!]!
}

type User {
	userId: ID!
	username: String!
	contact: String!
	email: String!
	role: String
}
